#spring.application.name=aws_auth_test_251030
#
#server.port=8080
#
## Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/test2db
##spring.datasource.url=jdbc:mysql://[rds_mysql]:3306/[db이름]
#spring.datasource.username=root
#spring.datasource.password=12345
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA config
## SQL Query가 콘솔창에 출력되는 설정
#spring.jpa.properties.hibernate.show_sql=true
#
## SQL Query가 콘솔창에 가독성 좋게 변환해서 출력하는 설정
#spring.jpa.properties.hibernate.format_sql=true
#
## DB 에 테이블 생성 관련 옵션 설정
#spring.jpa.hibernate.ddl-auto=update
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://__:3306/authdb # RDS 인스턴스 엔드포인트
    username: admin # RDS 마스터 사용자 이름
    password: __ # RDS 마스터 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: ______ # IAM 통해서 발급받은 액세스 키
        secret-key: ______ # IAM 통해서 발급받은 비밀 액세스 키
      s3:
        bucket: __ # 생성한 버킷명
      region:
        static: ap-northeast-2